apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
  - name: "5433"
    port: 5433
    targetPort: 5432
  selector:
    io.kompose.service: postgres
status:
  loadBalancer: {}
